services:
  db:
    image: mysql:8.0
    container_name: insuredperson-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: insured_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insuredperson-app
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data: